name: Atualizacao Diaria Caixa

on:
  schedule:
    - cron: '0 11 * * *' # Equivale a 08:00 no horário de Brasília
  workflow_dispatch: # Permite que você dê o "Play" manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar codigo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Dependencias
        run: |
          pip install -r requirements.txt

      - name: Executar o Robo
        run: python robo_sipii_simples.py

      - name: Salvar Resultados no GitHub
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Dados atualizados via Robô: $(date)"
          git push
